language: node_js

node_js:
  - "4"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "nohup bash -c 'java -jar WebRTC/test/selenium-server-standalone-2.52.0.jar &'"
  - sleep 3 # give xvfb some time to start
script:
  - "ls"
  - "mongo coderdojo initialize.js"
  - "cd WebRTC/"
  - sleep 5
  - "npm install"
  - "npm update"
  - "npm install forever -g"
  - "export XIRSYS=d61e9bc4-ef33-11e5-99b3-f77709746db4"
  - "forever start bin/www.js"
  - "npm test"
env:
  - CXX=g++-4.8
  
services:
  - mongodb
sudo: requireds

